<!DOCTYPE  html>
<head>
    <title>Site title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="css/main.css">
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
    
</head>
<body>

    <nav>
        <ul>
            <li><a href="?page=home" class="<?php echo ($page == 'home')? 'active' : ''; ?>">Home</a></li>
            <li><a href="?page=test" class="<?php echo ($page == 'test')? 'active' : ''; ?>">Test</a></li>
            
        </ul>
    </nav>
    <div class="main">